name: Python Pipeline

on: push

jobs:
 test:
  runs-on: ubuntu-latest
  
  steps:
    - run : | 
       env | sort
       ls -al
    - uses: actions/checkout@v2
    - run: |
       cat hello.py
       python hello.py
   
 build:
  needs: [test]
  runs-on: ubuntu-latest
  steps: 
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v2
      with:
       name: hello
       path: .
